// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzxwaisogphtvwdfotkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6eHdhaXNvZ3BodHZ3ZGZvdGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDY4MTksImV4cCI6MjA2MTUyMjgxOX0.DabHh1ZJVE7Y383e-xRLHlEKIEHWVjBQuQR2PQOMMjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);